const CHANGE_COLLAPSED = 'CHANGE_COLLAPSED';
const USER_LOGIN_STATUS = 'USER_LOGIN_STATUS';
const CHANGE_OPEN_KEYS = 'CHANGE_OPEN_KEYS';

export { CHANGE_COLLAPSED, USER_LOGIN_STATUS, CHANGE_OPEN_KEYS };
